In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import os
import matplotlib.font_manager as fm
import yfinance as yf
import datetime
from datetime import timedelta, datetime
import openpyxl
import setuptools
import pandas_datareader as pdr

In [2]:
dfMENSAL = pd.read_excel('BASE_MENSAL_GARE_MAR.xlsx')
dfCOMPRA = dfMENSAL.query('OPERAÇÃO == "Compra"')
dfVENDA = dfMENSAL.query('OPERAÇÃO == "Venda"')

dfCOMPRA_final = dfCOMPRA.groupby(['DOCUMENTO'], as_index=False).agg({'DOCUMENTO':'first','NOME':'first','PF_PJ':'first','TOTAL':'first','TOTAL_NOVO':'last','VAR_COTAS':'sum',
                                                                      'OPERAÇÃO':'first','FINANCEIRO_ATUAL':'first','FINANCEIRO_NOVO':'last', 'VAR_PRECO':'sum','CATEGORIAS ATUAIS':'last',
                                                                      'CATEGORIAS ANTIGAS':'first','Participação_sup':'sum','GARE15':'first','GALG15':'first',
                                                                      'CATEGORIAS':'first'})
                                                                                                                            
dfVENDA_final = dfVENDA.groupby(['DOCUMENTO'], as_index=False).agg({'DOCUMENTO':'first','NOME':'first','PF_PJ':'first','TOTAL':'first','TOTAL_NOVO':'last','VAR_COTAS':'sum',
                                                                    'OPERAÇÃO':'first','FINANCEIRO_ATUAL':'first','FINANCEIRO_NOVO':'last','VAR_PRECO':'sum','CATEGORIAS ATUAIS':'last',
                                                                    'CATEGORIAS ANTIGAS':'first','Participação_sup':'sum','GARE15':'first','GALG15':'first',
                                                                    'CATEGORIAS':'first'})

total_compra = dfCOMPRA['VAR_PRECO'].sum()
total_venda = dfVENDA['VAR_PRECO'].sum()
delta_sum = total_compra+total_venda
print('o valor de compra é {} e o valor de venda é {}, e o total é {}'.format(total_compra, total_venda, delta_sum))

o valor de compra é 58001553.56 e o valor de venda é 58001553.56000001, e o total é 116003107.12

In [3]:
dfCOMPRA_PJ = dfCOMPRA_final.query('PF_PJ == "PJ"')
dfVENDA_PJ = dfVENDA_final.query('PF_PJ == "PJ"')
dfCOMPRA_PJ_VAR_PRECO = dfCOMPRA_PJ['VAR_PRECO'].sum()
dfVENDA_PJ_VAR_PRECO = dfVENDA_PJ['VAR_PRECO'].sum()
part_pj_compra = (dfCOMPRA_PJ_VAR_PRECO/total_compra)*100
part_pj_venda = (dfVENDA_PJ_VAR_PRECO/total_venda)*100
print('o valor comprado por PJs foi {}, e participação no vol total foi {} e o vendido foi {}, e participação no vol total foi {}'.format(dfCOMPRA_PJ_VAR_PRECO, part_pj_compra, dfVENDA_PJ_VAR_PRECO, part_pj_venda))

o valor comprado por PJs foi 2412856.04, e participação no vol total foi 4.159985193334535 e o vendido foi 11041898.81, e participação no vol total foi 19.03724664646724

In [4]:
dfCOMPRA_PF = dfCOMPRA.query('PF_PJ == "PF"')
dfVENDA_PF = dfVENDA.query('PF_PJ == "PF"')
dfCOMPRA_PF_VAR_PRECO = dfCOMPRA_PF['VAR_PRECO'].sum()
dfVENDA_PF_VAR_PRECO = dfVENDA_PF['VAR_PRECO'].sum()
part_pf_compra = (dfCOMPRA_PF_VAR_PRECO/total_compra)*100
part_pf_venda = (dfVENDA_PF_VAR_PRECO/total_venda)*100
print('o valor comprado por PFs foi {}, e participação no vol total foi {} e o vendido foi {}, e participação no vol total foi {}'.format(dfCOMPRA_PF_VAR_PRECO, part_pf_compra, dfVENDA_PF_VAR_PRECO, part_pf_venda))

o valor comprado por PFs foi 55588697.519999996, e participação no vol total foi 95.84001480666545 e o vendido foi 46959654.75, e participação no vol total foi 80.96275335353275

In [5]:
segrega_cotas_C = dfCOMPRA_PJ.groupby(by = ['CATEGORIAS ANTIGAS'])['VAR_PRECO'].sum()
segrega_cotas_C = segrega_cotas_C.sort_values(ascending=False)
segrega_cotas_C_df = segrega_cotas_C.reset_index()
segrega_cotas_C_df

  CATEGORIAS ANTIGAS   VAR_PRECO
0          100k-500k  1420956.36
1           50k-100k   460903.16
2            20k-50k   249563.80
3             5k-20k   149478.20
4            500k-1M    48056.43
5              1k-5k    42214.69
6               0-1k    41683.40

In [6]:
segrega_cotas_V = dfVENDA_PJ.groupby(by = ['CATEGORIAS ANTIGAS'])['VAR_PRECO'].sum()
segrega_cotas_V = segrega_cotas_V.sort_values(ascending=False)
segrega_cotas_V_df = segrega_cotas_V.reset_index()
segrega_cotas_V_df

  CATEGORIAS ANTIGAS   VAR_PRECO
0               >15M  4748577.90
1             3M-15M  4158152.18
2           50k-100k  1257507.36
3            500k-1M   410605.46
4            20k-50k   162650.23
5          100k-500k   154709.64
6             5k-20k    73887.38
7              1k-5k    43269.49
8               0-1k    32539.17

In [7]:
dfCOMPRA_PJ

,DOCUMENTO,NOME,PF_PJ,TOTAL,TOTAL_NOVO,VAR_COTAS,OPERAÇÃO,FINANCEIRO_ATUAL,FINANCEIRO_NOVO,VAR_PRECO,CATEGORIAS ATUAIS,CATEGORIAS ANTIGAS,Participação_sup,GARE15,GALG15,CATEGORIAS
103113,133590000120,BRASCHIL UNIFORMES E EQUIPAMENTOS LTDA,PJ,630,633,3,Compra,5304.60,5329.86,25.26,5k-20k,5k-20k,0.000363,AUSENTE,AUSENTE,3
103114,2332886000104,XP INVESTIMENTOS CCTVM S/A,PJ,3164,19173,25922,Compra,25217.08,165846.45,218608.87,100k-500k,20k-50k,3.541561,AUSENTE,AUSENTE,4
103115,2391347000138,MARCELO H.M.DE BRITO E CIA LTDA,PJ,0,86,86,Compra,0.00,732.72,732.72,0-1k,0-1k,0.012325,GARE15,GALG15,1
103116,3795619000128,DO VALE PRUDENTE PNEUS E RECAPAGENS LTDA,PJ,200,310,110,Compra,1684.00,2610.20,926.20,1k-5k,1k-5k,0.013316,AUSENTE,AUSENTE,2
103117,4616973000100,LCJ IMPORTACAO E COMERCIO DE PNEUS LTDA,PJ,210,300,90,Compra,1768.20,2526.00,757.80,1k-5k,1k-5k,0.010895,AUSENTE,AUSENTE,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103188,57638757000122,BBX EMPREENDIMENTOS E PARTICIPACOES LTDA,PJ,0,900,900,Compra,0.00,7371.00,7371.00,5k-20k,5k-20k,0.150914,AUSENTE,AUSENTE,3
103189,58931172000169,PONCIANO REIS PATRIMONIAL LTDA,PJ,13,100,87,Compra,110.11,848.00,737.39,0-1k,0-1k,0.008640,AUSENTE,AUSENTE,1
103190,64076078000172,SETTIMO ENGENHARIA DE CONSTRUCOES LTDA,PJ,0,203,203,Compra,0.00,1693.02,1693.02,1k-5k,1k-5k,0.035573,AUSENTE,AUSENTE,2
103191,72892284000189,BWA- LOCACAO DE VEICULOS LTDA,PJ,398,401,3,Compra,3199.92,3224.04,24.12,1k-5k,1k-5k,0.000347,AUSENTE,AUSENTE,2
103192,85496941000110,LUIZ COLOMBO JUNIOR E CIA LTDA,PJ,500,750,250,Compra,4210.00,6315.00,2105.00,5k-20k,1k-5k,0.030263,AUSENTE,AUSENTE,2

In [8]:
cat = 'CATEGORIAS'
cat_atuais = 'CATEGORIAS ATUAIS'
Nome = 'NOME'
fin_mov = 'VAR_PRECO'
qtde = 'TOTAL_NOVO'

t10c = dfCOMPRA_PJ.sort_values(by = ['VAR_PRECO'], ascending=False).iloc[:20, :]
t10c = t10c.drop(columns=['DOCUMENTO', 'TOTAL', 'VAR_COTAS', 'OPERAÇÃO', 'FINANCEIRO_ATUAL', 'Participação_sup', 'GARE15', 'GALG15', 'CATEGORIAS'])
t10c

,NOME,PF_PJ,TOTAL_NOVO,FINANCEIRO_NOVO,VAR_PRECO,CATEGORIAS ATUAIS,CATEGORIAS ANTIGAS
103165,XTX MARKETS TRADING LIMITED,PJ,95634,827234.10,1199538.15,500k-1M,100k-500k
103146,RIGEL COVE LP,PJ,5311,45674.60,460903.16,20k-50k,50k-100k
103157,TREND ETF IFIX FUNDO DE INDICE,PJ,30830,266679.50,221418.21,100k-500k,100k-500k
103114,XP INVESTIMENTOS CCTVM S/A,PJ,19173,165846.45,218608.87,100k-500k,20k-50k
103187,DOCA CONSULTING BRASIL LTDA,PJ,5800,49358.00,49358.00,20k-50k,5k-20k
103180,XP HEDGE FUND FUNDO DE INVESTIMENTO IMOBILIRIO...,PJ,87210,709017.30,48056.43,500k-1M,500k-1M
103158,JUMP TRADING EUROPE B.V.,PJ,1201,10220.51,33951.11,5k-20k,5k-20k
103155,MORGAN STANLEY URUGUAY LTDA,PJ,290,2508.50,33064.54,1k-5k,1k-5k
103119,"UBS AG, LONDON BRANCH",PJ,138,1170.24,30288.27,1k-5k,20k-50k
103120,GOLDMAN SACHS INTERNATIONAL,PJ,3713,30409.47,30237.48,20k-50k,0-1k
103131,M MARIA DE ANDRADE SILVA,PJ,2087,17948.20,17948.20,5k-20k,5k-20k
103123,INB TECNOLOGIA,PJ,1819,15406.93,15406.93,5k-20k,5k-20k
103161,ZAZA HOLDING FAMILIAR E PARTICIPACOES LTDA.,PJ,1443,12481.95,12481.95,5k-20k,5k-20k
103188,BBX EMPREENDIMENTOS E PARTICIPACOES LTDA,PJ,900,7371.00,7371.00,5k-20k,5k-20k
103135,APORTO CONSULTORIA EIRELI,PJ,639,5437.89,5437.89,5k-20k,5k-20k
103160,ONE MANAGEMENT PROJETOS LTDA,PJ,1756,14785.52,5009.90,5k-20k,5k-20k
103166,CREDIT SUISSE (BRASIL) S.A. CTVM,PJ,381,3246.12,4578.27,1k-5k,0-1k
103192,LUIZ COLOMBO JUNIOR E CIA LTDA,PJ,750,6315.00,2105.00,5k-20k,1k-5k
103190,SETTIMO ENGENHARIA DE CONSTRUCOES LTDA,PJ,203,1693.02,1693.02,1k-5k,1k-5k
103122,COLOMBO PNEUS E RECAPAGENS LTDA,PJ,340,2862.80,1178.80,1k-5k,1k-5k

In [9]:
cat = 'CATEGORIAS'
cat_atuais = 'CATEGORIAS ATUAIS'
Nome = 'NOME'
fin_mov = 'VAR_PRECO'
qtde = 'TOTAL_NOVO'

t10v = dfVENDA_PJ.sort_values(by = ['VAR_PRECO'], ascending=False).iloc[:20, :]
t10v = t10v.drop(columns=['DOCUMENTO', 'TOTAL', 'VAR_COTAS', 'OPERAÇÃO', 'FINANCEIRO_ATUAL', 'Participação_sup', 'GARE15', 'GALG15', 'CATEGORIAS'])
t10v

,NOME,PF_PJ,TOTAL_NOVO,FINANCEIRO_NOVO,VAR_PRECO,CATEGORIAS ATUAIS,CATEGORIAS ANTIGAS
18341,AAA FUNDO DE INVESTIMENTO MULTIMERCADO CREDITO...,PJ,6720866,58135490.90,4748577.90,>15M,>15M
18330,CAPITANIA SECURITIES II FDO IN,PJ,0,0.00,3153967.32,0-1k,3M-15M
18356,DAYCOVAL D9 FUNDO DE INVESTIMENTO IMOBILIRIO,PJ,302631,2508810.99,1004184.86,1M-3M,3M-15M
18347,XTX MARKETS TRADING LIMITED,PJ,70480,599784.80,488621.22,500k-1M,50k-100k
18337,RIGEL COVE LP,PJ,0,0.00,462231.59,0-1k,50k-100k
18360,CSR PARTICIPACAO LTDA,PJ,40316,348733.40,410605.46,100k-500k,500k-1M
18344,TREND ETF IFIX FUNDO DE INDICE,PJ,22396,190589.96,154709.64,100k-500k,100k-500k
18350,LANNER ELETRONICA LTDA,PJ,0,0.00,91190.00,0-1k,50k-100k
18359,CENTRO SUL REPRES COM IMPE EXP LTDA,PJ,0,0.00,91190.00,0-1k,50k-100k
18314,XP INVESTIMENTOS CCTVM S/A,PJ,16714,142236.14,81790.65,100k-500k,20k-50k
18352,LMVB ADMINISTRACAO DE BENS LTDA,PJ,0,0.00,67530.55,0-1k,50k-100k
18357,MJM MANUTENCAO E REPARACAO DE CALDEIRAS EIRELI,PJ,0,0.00,56744.00,0-1k,50k-100k
18345,JUMP TRADING EUROPE B.V.,PJ,0,0.00,34412.48,0-1k,5k-20k
18343,MORGAN STANLEY URUGUAY LTDA,PJ,0,0.00,33280.39,0-1k,1k-5k
18316,GOLDMAN SACHS INTERNATIONAL,PJ,0,0.00,30778.66,0-1k,20k-50k
18315,"UBS AG, LONDON BRANCH",PJ,6,51.90,30767.46,0-1k,0-1k
18336,GGR COVEPI RENDA FII,PJ,0,0.00,25977.48,0-1k,20k-50k
18329,M MARIA DE ANDRADE SILVA,PJ,0,0.00,23966.76,0-1k,20k-50k
18334,PETRAGLIA - ADVOGADOS ASSOCIADOS,PJ,0,0.00,17919.60,0-1k,5k-20k
18339,KEART COMERCIO LTDA,PJ,0,0.00,8480.00,0-1k,5k-20k